---
- name: Install build dependencies
  apt: name="{{ item }}"
  with_items:
    - dkms

- name: Clone driver source
  git: repo=https://github.com/amzn/amzn-drivers
       dest="/usr/src/amzn-drivers-{{ aws_ena_driver_version}}"
       version="ena_linux_{{ aws_ena_driver_version }}"

- name: Create DKMS conf file
  template: src=dkms.conf.j2
            dest="/usr/src/amzn-drivers-{{ aws_ena_driver_version}}/dkms.conf"

- name: Add module to DKMS
  command: "dkms add -m amzn-drivers -v {{ aws_ena_driver_version}}"
  tags:
    - skip_ansible_lint

- name: Build module
  command: "dkms build -m amzn-drivers -v {{ aws_ena_driver_version}}"
  tags:
    - skip_ansible_lint

- name: Install module
  command: "dkms install -m amzn-drivers -v {{ aws_ena_driver_version}}"
  tags:
    - skip_ansible_lint

- name: Load module at boot time
  command: update-initramfs -c -k all
  tags:
    - skip_ansible_lint